set(GLADE_FILE ${CMAKE_ARGV3})
set(RESULT_HEADER ${CMAKE_ARGV4})
set(VAR_NAME ${CMAKE_ARGV5})
set(HEADER_IN ${CMAKE_ARGV6})

file(READ ${GLADE_FILE} GLADE_SOURCE_CONTENT)
string(REGEX REPLACE "\n *" "" GLADE_SOURCE_CONTENT ${GLADE_SOURCE_CONTENT})

configure_file(${HEADER_IN} ${RESULT_HEADER} ESCAPE_QUOTES)
